name: Keep Supabase Awake

on:
  schedule:
    - cron: "0 2 * * *"  # 2AM everyday
  workflow_dispatch:       # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl awake
        run: |
              response=$(curl --silent --show-error --max-time 8 --connect-timeout 5 "https://rankbee.vercel.app/api/awake")
              echo "Response body:"
              echo "$response"
              
