name: Keep Supabase Awake

on:
  schedule:
    - cron: "0 2 * * *"  # 2AM everyday
  workflow_dispatch:       # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping account page
        run: |
              response=$(curl --write-out '%{http_code}' --silent --output /dev/null \
              --max-time 8 --connect-timeout 5 "https://rankbee.vercel.app/api/awake")
              echo "Ping response: $response"
              
