name: Keep Render Server Awake

on:
  schedule:
    - cron: "*/8 * * * *" 
  workflow_dispatch:     

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping multiple URLs with timeout
        run: |
          URLs=(
            "https://event-management-system-li2e.onrender.com"
            "https://meroshop.onrender.com"
          )

          for url in "${URLs[@]}"; do
          echo "Pinging $url"
          curl --silent --max-time 5 --connect-timeout 3 --output /dev/null "$url"
          done
