name: Keep Render Server Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl your Render server
        run: curl -s https://event-management-system-li2e.onrender.com > /dev/null
